apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: qwen3-1
  namespace: swap
  labels:
    runai/queue: swap
  annotations:
    swap-coordinator/min-warm-workers: "2"
    swap-coordinator/max-warm-workers: "2"
spec:
  services:

    Frontend:
      labels:
        runai/queue: swap
      componentType: frontend
      extraPodMetadata:
        labels:
          runai/queue: swap
          swap-coordinator/frontend: qwen3-1
      replicas: 1
      envs:
        - name: DYN_ROUTER_MODE
          value: kv
        - name: DYN_SWAP_COORDINATOR_URL
          value: "http://swap-coordinator-service.swap.svc.cluster.local:8080"
        - name: DYN_SWAP_COORDINATOR_TIMEOUT
          value: "1.0"
      extraPodSpec:
        mainContainer:
          image: vllm-runtime:1.0.1-swap
          imagePullPolicy: IfNotPresent
          name: ""
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          volumeMounts:
          - name: swap-frontend-code
            mountPath: /opt/dynamo/venv/lib/python3.12/site-packages/dynamo/frontend/frontend_args.py
            subPath: frontend_args.py
          - name: swap-frontend-code
            mountPath: /opt/dynamo/venv/lib/python3.12/site-packages/dynamo/frontend/vllm_processor.py
            subPath: vllm_processor.py
          - name: swap-frontend-code
            mountPath: /opt/dynamo/venv/lib/python3.12/site-packages/dynamo/frontend/swap_routing.py
            subPath: swap_routing.py
          - name: swap-frontend-code
            mountPath: /opt/dynamo/venv/lib/python3.12/site-packages/dynamo/frontend/sglang_processor.py
            subPath: sglang_processor.py
        nodeSelector:
          run.ai/swap-enabled: 'true'
        schedulerName: runai-scheduler
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        volumes:
        - name: swap-frontend-code
          configMap:
            name: swap-frontend-code

    vLLMWorker:
      labels:
        runai/queue: swap
      componentType: worker
      envFromSecret: hf-token-secret
      replicas: 4
      extraPodMetadata:
        labels:
          runai/queue: swap
          model: qwen3-1
        annotations:
          gpu-fraction: "0.3"
          gpu-fraction-num-devices: "3"
      extraPodSpec:
        mainContainer:
          env:
          - name: VLLM_ENGINE_ITERATION_TIMEOUT_S
            value: "120"
          - name: RUNAI_GPU_MEMORY_LIMIT
            value: "1.0"
          - name: RUNAI_SWAP_MAX_BLOCK_SIZE_MB
            value: "512"
          image: vllm-runtime:1.0.1-swap
          imagePullPolicy: IfNotPresent
          name: ""
          workingDir: /workspace/
          command:
          - python3
          - -m
          - dynamo.vllm
          args:
          - --model
          - Qwen/Qwen3-0.6B
          - --served-model-name
          - Qwen/Qwen3-0.6B
          - --kv-events-config 
          - '{"enable_kv_cache_events":true,"publisher":"zmq","endpoint":"tcp://*:20080"}'
          - --block-size
          - "16"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
        nodeSelector:                                                                                                                                                   
          run.ai/swap-enabled: 'true'
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  model: qwen3-1
              topologyKey: kubernetes.io/hostname
        schedulerName: runai-scheduler
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        volumes:
        - emptyDir: {}
          name: triton-cache
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-1-frontend-nodeport
  namespace: swap
spec:
  type: NodePort
  selector:
    swap-coordinator/frontend: qwen3-1
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30081
    protocol: TCP
