//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoWorkerMetadata) DeepCopyInto(out *DynamoWorkerMetadata) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoWorkerMetadata.
func (in *DynamoWorkerMetadata) DeepCopy() *DynamoWorkerMetadata {
	if in == nil {
		return nil
	}
	out := new(DynamoWorkerMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoWorkerMetadata) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoWorkerMetadataList) DeepCopyInto(out *DynamoWorkerMetadataList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamoWorkerMetadata, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoWorkerMetadataList.
func (in *DynamoWorkerMetadataList) DeepCopy() *DynamoWorkerMetadataList {
	if in == nil {
		return nil
	}
	out := new(DynamoWorkerMetadataList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamoWorkerMetadataList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoWorkerMetadataSpec) DeepCopyInto(out *DynamoWorkerMetadataSpec) {
	*out = *in
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoWorkerMetadataSpec.
func (in *DynamoWorkerMetadataSpec) DeepCopy() *DynamoWorkerMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoWorkerMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoWorkerMetadataStatus) DeepCopyInto(out *DynamoWorkerMetadataStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoWorkerMetadataStatus.
func (in *DynamoWorkerMetadataStatus) DeepCopy() *DynamoWorkerMetadataStatus {
	if in == nil {
		return nil
	}
	out := new(DynamoWorkerMetadataStatus)
	in.DeepCopyInto(out)
	return out
}
